# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignalSlot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1931, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ShowLabel = QtWidgets.QLabel(self.centralwidget)
        self.ShowLabel.setGeometry(QtCore.QRect(0, 50, 1280, 720))
        self.ShowLabel.setObjectName("ShowLabel")
        self.yolo_label = QtWidgets.QLabel(self.centralwidget)
        self.yolo_label.setGeometry(QtCore.QRect(1280, 70, 640, 360))
        self.yolo_label.setObjectName("yolo_label")
        self.depth_label = QtWidgets.QLabel(self.centralwidget)
        self.depth_label.setGeometry(QtCore.QRect(1280, 600, 640, 360))
        self.depth_label.setObjectName("depth_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 0, 752, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.close_button = QtWidgets.QPushButton(self.layoutWidget)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_3.addWidget(self.close_button)
        self.open_camera = QtWidgets.QPushButton(self.layoutWidget)
        self.open_camera.setEnabled(False)
        self.open_camera.setObjectName("open_camera")
        self.horizontalLayout_3.addWidget(self.open_camera)
        self.thread_open = QtWidgets.QPushButton(self.layoutWidget)
        self.thread_open.setEnabled(False)
        self.thread_open.setObjectName("thread_open")
        self.horizontalLayout_3.addWidget(self.thread_open)
        self.thread_close = QtWidgets.QPushButton(self.layoutWidget)
        self.thread_close.setEnabled(False)
        self.thread_close.setObjectName("thread_close")
        self.horizontalLayout_3.addWidget(self.thread_close)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_fps = QtWidgets.QLabel(self.layoutWidget)
        self.label_fps.setObjectName("label_fps")
        self.horizontalLayout.addWidget(self.label_fps)
        self.info_lab = QtWidgets.QLabel(self.layoutWidget)
        self.info_lab.setObjectName("info_lab")
        self.horizontalLayout.addWidget(self.info_lab)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(1280, 430, 640, 150))
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.imu_label = QtWidgets.QLabel(self.centralwidget)
        self.imu_label.setGeometry(QtCore.QRect(810, 10, 321, 21))
        self.imu_label.setObjectName("imu_label")
        self.receive_data_label = QtWidgets.QLabel(self.centralwidget)
        self.receive_data_label.setGeometry(QtCore.QRect(71, 881, 181, 121))
        self.receive_data_label.setObjectName("receive_data_label")
        self.send_data_label = QtWidgets.QLabel(self.centralwidget)
        self.send_data_label.setGeometry(QtCore.QRect(280, 880, 501, 111))
        self.send_data_label.setObjectName("send_data_label")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 840, 243, 35))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open_serial_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.open_serial_button.setObjectName("open_serial_button")
        self.horizontalLayout_4.addWidget(self.open_serial_button)
        self.close_serial_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.close_serial_button.setObjectName("close_serial_button")
        self.horizontalLayout_4.addWidget(self.close_serial_button)
        self.info_serial = QtWidgets.QLabel(self.layoutWidget1)
        self.info_serial.setObjectName("info_serial")
        self.horizontalLayout_4.addWidget(self.info_serial)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.info_result = QtWidgets.QLabel(self.centralwidget)
        self.info_result.setGeometry(QtCore.QRect(350, 816, 311, 81))
        font = QtGui.QFont()
        font.setFamily("Suruma")
        font.setPointSize(20)
        self.info_result.setFont(font)
        self.info_result.setObjectName("info_result")
        self.label_obj1 = QtWidgets.QLabel(self.centralwidget)
        self.label_obj1.setGeometry(QtCore.QRect(1280, 430, 120, 120))
        self.label_obj1.setObjectName("label_obj1")
        self.label_obj2 = QtWidgets.QLabel(self.centralwidget)
        self.label_obj2.setGeometry(QtCore.QRect(1400, 430, 120, 120))
        self.label_obj2.setObjectName("label_obj2")
        self.label_obj3 = QtWidgets.QLabel(self.centralwidget)
        self.label_obj3.setGeometry(QtCore.QRect(1520, 430, 120, 120))
        self.label_obj3.setObjectName("label_obj3")
        self.fire1 = QtWidgets.QLabel(self.centralwidget)
        self.fire1.setGeometry(QtCore.QRect(1640, 430, 120, 120))
        self.fire1.setObjectName("fire1")
        self.fire2 = QtWidgets.QLabel(self.centralwidget)
        self.fire2.setGeometry(QtCore.QRect(1760, 430, 120, 120))
        self.fire2.setObjectName("fire2")
        self.info_obj1 = QtWidgets.QLabel(self.centralwidget)
        self.info_obj1.setGeometry(QtCore.QRect(1280, 550, 120, 50))
        self.info_obj1.setObjectName("info_obj1")
        self.info_obj2 = QtWidgets.QLabel(self.centralwidget)
        self.info_obj2.setGeometry(QtCore.QRect(1400, 550, 120, 50))
        self.info_obj2.setObjectName("info_obj2")
        self.info_obj3 = QtWidgets.QLabel(self.centralwidget)
        self.info_obj3.setGeometry(QtCore.QRect(1520, 550, 120, 50))
        self.info_obj3.setObjectName("info_obj3")
        self.info_obj4 = QtWidgets.QLabel(self.centralwidget)
        self.info_obj4.setGeometry(QtCore.QRect(1640, 550, 120, 50))
        self.info_obj4.setObjectName("info_obj4")
        self.info_obj5 = QtWidgets.QLabel(self.centralwidget)
        self.info_obj5.setGeometry(QtCore.QRect(1760, 550, 120, 50))
        self.info_obj5.setObjectName("info_obj5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1931, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.close_button.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ShowLabel.setText(_translate("MainWindow", "color"))
        self.yolo_label.setText(_translate("MainWindow", "yolo"))
        self.depth_label.setText(_translate("MainWindow", "depth"))
        self.close_button.setText(_translate("MainWindow", "关闭窗口"))
        self.open_camera.setText(_translate("MainWindow", "开启相机"))
        self.thread_open.setText(_translate("MainWindow", "开启子线程"))
        self.thread_close.setText(_translate("MainWindow", "关闭子线程"))
        self.label_fps.setText(_translate("MainWindow", "帧率："))
        self.info_lab.setText(_translate("MainWindow", "信息"))
        self.label_2.setText(_translate("MainWindow", "陀螺仪"))
        self.imu_label.setText(_translate("MainWindow", "imu"))
        self.receive_data_label.setText(_translate("MainWindow", "receive data"))
        self.send_data_label.setText(_translate("MainWindow", "send data"))
        self.open_serial_button.setText(_translate("MainWindow", "打开串口"))
        self.close_serial_button.setText(_translate("MainWindow", "关闭串口"))
        self.info_serial.setText(_translate("MainWindow", "info"))
        self.info_result.setText(_translate("MainWindow", "识别结果及距离"))
        self.label_obj1.setText(_translate("MainWindow", "           obj1"))
        self.label_obj2.setText(_translate("MainWindow", "           obj2"))
        self.label_obj3.setText(_translate("MainWindow", "            obj3"))
        self.fire1.setText(_translate("MainWindow", "           fire1"))
        self.fire2.setText(_translate("MainWindow", "fire2"))
        self.info_obj1.setText(_translate("MainWindow", "       info_obj1"))
        self.info_obj2.setText(_translate("MainWindow", "       info_obj2"))
        self.info_obj3.setText(_translate("MainWindow", "       info_obj3"))
        self.info_obj4.setText(_translate("MainWindow", "       fire_obj1"))
        self.info_obj5.setText(_translate("MainWindow", "       fire_obj2"))

